apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-python-flask-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-python-flask-web-app
spec:
  source:
    git:
      url: https://git@github.com:zCHIP/github.com:zCHIP/tap-python-flask-app
      ref:
        branch: master